module.exports = {
  SET_CONFIG: 'SET_CONFIG',

  SET_SERIAL_STATUS: 'SET_SERIAL_STATUS',

  UPDATE_VARIABLE: 'UPDATE_VARIABLE',

  SET_MESSAGE_COUNT: 'SET_MESSAGE_COUNT',
  ADD_MESSAGE: 'ADD_MESSAGE',
};
