export const SET_CONFIG = 'SET_CONFIG';

export const SET_SERIAL_STATUS = 'SET_SERIAL_STATUS';

export const UPDATE_VARIABLE = 'UPDATE_VARIABLE';
export const OUTPUT_VARIABLES = 'OUTPUT_VARIABLES';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const OUTPUT_MESSAGES = 'OUTPUT_MESSAGES';
export const SET_MESSAGE_COUNT = 'SET_MESSAGE_COUNT';
