export const SET_CONFIG = 'SET_CONFIG';

export const SET_SERIAL_STATUS = 'SET_SERIAL_STATUS';

export const UPDATE_VARIABLE = 'UPDATE_VARIABLE';

export const SET_MESSAGE_COUNT = 'SET_MESSAGE_COUNT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
